
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVISION MULTIPLICACION NUMERO PARENTESIS_DER PARENTESIS_IZQ RESTA SUMAexpresion : termino\n                  | termino SUMA expresion\n                  | termino RESTA expresiontermino : factor\n               | factor MULTIPLICACION termino\n               | factor DIVISION terminofactor : NUMERO\n              | PARENTESIS_IZQ expresion PARENTESIS_DER'
    
_lr_action_items = {'NUMERO':([0,5,6,7,8,9,],[4,4,4,4,4,4,]),'PARENTESIS_IZQ':([0,5,6,7,8,9,],[5,5,5,5,5,5,]),'$end':([1,2,3,4,11,12,13,14,15,],[0,-1,-4,-7,-2,-3,-5,-6,-8,]),'PARENTESIS_DER':([2,3,4,10,11,12,13,14,15,],[-1,-4,-7,15,-2,-3,-5,-6,-8,]),'SUMA':([2,3,4,13,14,15,],[6,-4,-7,-5,-6,-8,]),'RESTA':([2,3,4,13,14,15,],[7,-4,-7,-5,-6,-8,]),'MULTIPLICACION':([3,4,15,],[8,-7,-8,]),'DIVISION':([3,4,15,],[9,-7,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expresion':([0,5,6,7,],[1,10,11,12,]),'termino':([0,5,6,7,8,9,],[2,2,2,2,13,14,]),'factor':([0,5,6,7,8,9,],[3,3,3,3,3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expresion","S'",1,None,None,None),
  ('expresion -> termino','expresion',1,'p_expresion','untitled1.py',34),
  ('expresion -> termino SUMA expresion','expresion',3,'p_expresion','untitled1.py',35),
  ('expresion -> termino RESTA expresion','expresion',3,'p_expresion','untitled1.py',36),
  ('termino -> factor','termino',1,'p_termino','untitled1.py',40),
  ('termino -> factor MULTIPLICACION termino','termino',3,'p_termino','untitled1.py',41),
  ('termino -> factor DIVISION termino','termino',3,'p_termino','untitled1.py',42),
  ('factor -> NUMERO','factor',1,'p_factor','untitled1.py',46),
  ('factor -> PARENTESIS_IZQ expresion PARENTESIS_DER','factor',3,'p_factor','untitled1.py',47),
]
